return {
 	['[FRAME007]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 40,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",79,},
	},
	['[FRAME008]'] = {
		['[DELAY]'] = 40,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",80,},
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[RGBA]'] = {188,143,143,255,},
	},
	['[FRAME005]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 40,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",77,},
	},
	['[FRAME014]'] = {
		['[DELAY]'] = 80,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-207,-296,},
		['[ATTACK BOX]'] = {-97,-50,-7,189,100,172,},
		['[IMAGE]'] = {"character/swordman/effect/bloodriven/riven_circle.img",3,},
	},
	['[FRAME004]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 40,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",77,},
	},
	['[FRAME002]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 40,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",76,},
	},
	['[FRAME000]'] = {
		['[DELAY]'] = 40,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[PLAY SOUND]'] = {"sm_bloodriven_01","bloodriven_cast",},
		['[DAMAGE BOX]'] = {-30,-10,-6,71,20,101,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",75,},
	},
	['[FRAME009]'] = {
		['[DELAY]'] = 80,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",81,},
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[RGBA]'] = {255,0,0,255,},
	},
	['[FRAME MAX]'] = 17,
	['[FRAME013]'] = {
		['[DELAY]'] = 80,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-207,-296,},
		['[ATTACK BOX]'] = {-97,-50,-7,189,100,172,},
		['[IMAGE]'] = {"character/swordman/effect/bloodriven/riven_circle.img",2,},
	},
	['[FRAME006]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 40,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",78,},
	},
	['[FRAME003]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 40,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",76,},
	},
	['[FRAME001]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 40,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",75,},
	},
	['[FRAME016]'] = {
		['[DELAY]'] = 80,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-207,-296,},
		['[ATTACK BOX]'] = {-97,-50,-7,189,100,172,},
		['[IMAGE]'] = {"character/swordman/effect/bloodriven/riven_circle.img",5,},
	},
	['[FRAME015]'] = {
		['[DELAY]'] = 80,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-207,-296,},
		['[ATTACK BOX]'] = {-97,-50,-7,189,100,172,},
		['[IMAGE]'] = {"character/swordman/effect/bloodriven/riven_circle.img",4,},
	},
	['[FRAME010]'] = {
		['[DELAY]'] = 80,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",82,},
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[RGBA]'] = {255,0,0,255,},
	},
	['[FRAME011]'] = {
		['[DELAY]'] = 80,
		['[SET FLAG]'] = 1,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-207,-296,},
		['[PLAY SOUND]'] = "bloodriven_circle_01",
		['[ATTACK BOX]'] = {-97,-50,-7,189,100,172,},
		['[IMAGE]'] = {"character/swordman/effect/bloodriven/riven_circle.img",0,},
	},
	['[FRAME012]'] = {
		['[DELAY]'] = 80,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-207,-296,},
		['[ATTACK BOX]'] = {-97,-50,-7,189,100,172,},
		['[IMAGE]'] = {"character/swordman/effect/bloodriven/riven_circle.img",1,},
	},
 
}