return {
 	['[FRAME037]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",174,},
	},
	['[FRAME029]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",172,},
	},
	['[FRAME034]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",171,},
	},
	['[FRAME055]'] = {
		['[DELAY]'] = 600,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",176,},
	},
	['[FRAME021]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",167,},
	},
	['[FRAME045]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",201,},
	},
	['[FRAME052]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",177,},
	},
	['[FRAME042]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",198,},
	},
	['[FRAME016]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",159,},
	},
	['[FRAME006]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",161,},
	},
	['[FRAME053]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",178,},
	},
	['[FRAME043]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",199,},
	},
	['[FRAME017]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",160,},
	},
	['[FRAME007]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",162,},
	},
	['[FRAME014]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",163,},
	},
	['[FRAME035]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",172,},
	},
	['[FRAME004]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",159,},
	},
	['[FRAME026]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",172,},
	},
	['[FRAME058]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",179,},
	},
	['[FRAME048]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 80,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",204,},
	},
	['[FRAME050]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 120,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",205,},
	},
	['[FRAME063]'] = {
		['[DELAY]'] = 600,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",176,},
	},
	['[FRAME040]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",175,},
	},
	['[FRAME027]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",170,},
	},
	['[FRAME059]'] = {
		['[DELAY]'] = 600,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",176,},
	},
	['[FRAME049]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 80,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",205,},
	},
	['[FRAME024]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",170,},
	},
	['[FRAME051]'] = {
		['[DELAY]'] = 600,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",176,},
	},
	['[FRAME041]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",197,},
	},
	['[FRAME015]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",164,},
	},
	['[FRAME005]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",160,},
	},
	['[FRAME038]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",175,},
	},
	['[FRAME060]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",177,},
	},
	['[FRAME002]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",178,},
	},
	['[FRAME030]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",170,},
	},
	['[FRAME039]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",175,},
	},
	['[FRAME MAX]'] = 67,
	['[FRAME061]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",178,},
	},
	['[FRAME003]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",179,},
	},
	['[FRAME025]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",171,},
	},
	['[FRAME031]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",171,},
	},
	['[FRAME056]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",177,},
	},
	['[FRAME022]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",168,},
	},
	['[FRAME046]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",202,},
	},
	['[FRAME018]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",161,},
	},
	['[FRAME008]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",163,},
	},
	['[FRAME057]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",178,},
	},
	['[FRAME023]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",169,},
	},
	['[FRAME047]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",203,},
	},
	['[FRAME000]'] = {
		['[DELAY]'] = 600,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",176,},
	},
	['[FRAME054]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",179,},
	},
	['[FRAME019]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",165,},
	},
	['[FRAME044]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 900,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",200,},
	},
	['[FRAME009]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",164,},
	},
	['[FRAME066]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",179,},
	},
	['[FRAME065]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",178,},
	},
	['[FRAME064]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",177,},
	},
	['[FRAME062]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",179,},
	},
	['[FRAME013]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",162,},
	},
	['[FRAME036]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",173,},
	},
	['[FRAME028]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",171,},
	},
	['[FRAME001]'] = {
		['[DELAY]'] = 150,
		['[DAMAGE TYPE]'] = "normal",
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE BOX]'] = {-17,-5,0,30,10,107,},
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",177,},
	},
	['[FRAME010]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",159,},
	},
	['[FRAME032]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",172,},
	},
	['[FRAME033]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",170,},
	},
	['[FRAME011]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",160,},
	},
	['[LOOP]'] = 1,
	['[FRAME020]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",166,},
	},
	['[FRAME012]'] = {
		['[IMAGE POS]'] = {-232,-333,},
		['[DAMAGE TYPE]'] = "normal",
		['[DELAY]'] = 60,
		['[IMAGE]'] = {"character/swordman/equipment/avatar/skin/sm_body%04d.img",161,},
	},
 
}