---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2021/3/15 21:30
---
local _RESOURCE = require("engine.resource")
local _Base = require("engine.graphics.drawable.sprite")

---@class Entity.Drawable.Sprite : Engine.Graphics.Drawable.Sprite
local _Sprite = require("core.class")(_Base)

function _Sprite.HandleData(data)
	if data.path then
		data.spriteData = _RESOURCE.LoadSpriteData(data.path)
	end
end

function _Sprite:Ctor(data)
	_Base.Ctor(self, data.spriteData or nil)
end

return _Sprite