---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2021/1/31 1:28
---
local _Timer = require("utils.timer")
local _PositiveValue = require("utils.value")

local _MpModel = require("core.class")(_PositiveValue)

function _MpModel:Ctor(cur, max, varySpeed, regenTime)
	_PositiveValue.Ctor(self, cur, max, varySpeed)
	self._regenTime = regenTime or 500
	self._regenTimer = _Timer.New()
	self._regenEnable = false
end

function _MpModel:Update(dt)
	self._regenTimer:Tick(dt)
	if self._regenTimer.isRunning == false then
		self._regenEnable = true
	end
	if self._regenEnable then
		_PositiveValue.Update(self, dt)
	end
end

function _MpModel:Decrease(delta)
	_PositiveValue.Decrease(self, delta)
	--TODO:_regenEnable应该在切换至可以恢复MP的角色状态时通过event通知开启，所有component都需要添加Init方法来建立引用和注册事件监听。
	self._regenEnable = false
	self._regenTimer:Start(self._regenTime)
end

return _MpModel