---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2021/4/17 17:36
---

local _INPUT_DEFINE = {
	STATE = {
		PRESSED = 1,
		DOWN = 2,
		RELEASED = 3,
	},
	EVENT_TYPE = {
		ACTION = 1,
		AXIS = 2,
	},
	CONTROL_TYPE = {
		BUTTON = 1,
		AXIS = 2,
		AXIS_P = 3,
		AXIS_N = 4,
		DUAL_BUTTON = 5,
		AXIS_BUTTON = 6,
	},
}

return _INPUT_DEFINE