---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2019/8/11 23:52
---

local _Panel = require("system.gui.panels.panel")
local _Inventory = require("core.class")(_Panel) ---@class Inventory : Panel

function _Inventory:Ctor()
    _Panel.Ctor(self, "inventory")

    self:LoadLayout("Data/ui/layout/inventory")

    self.button = self:GetWidgetById("button1")
    self.button.eventClick:AddListener(nil, function() print("inventory button pressed.") end)

end

function _Inventory:Draw(x, y)


    _Panel.Draw(self, x, y)
end

function _Inventory:DispatchMessage(msg, x, y)


    _Panel.DispatchMessage(self, msg, x, y)
end

return _Inventory
