---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SerDing.
--- DateTime: 2019/8/24 21:45
---

local _Timer = require("Src.Core.Class")() ---@class Timer

function _Timer:Ctor(time, action)
    self.count = 0
    self.time = 0
    self.stop = false
    self.action = nil ---@type function
    self:Reset(time, action)
end

function _Timer:Tick(dt)
    if self.stop then
        return
    end

    self.count = self.count + dt
    if self.count >= self.time then
        self.action()
    end
end

function _Timer:SetTime(time)
    self.time = time
end

function _Timer:SetAction(action)
    self.action = action
end

function _Timer:Stop()
    self.stop = true
end

function _Timer:Continue()
    self.stop = false
end

function _Timer:Continue()
    self.stop = false
end

function _Timer:Cancel()
    self:Stop()
    self:Reset(0, nil)
end

function _Timer:Reset(time, action)
    self.count = 0
    self:SetTime(time)
    self:SetAction(action)
end

return _Timer
