---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SerDing.
--- DateTime: 2019/7/16 11:08
---

local _Vector3 = require "Src.Core.Class"()

---@param x number
---@param y number
---@param z number
function _Vector3:Ctor(x, y, z)
    self.x = x or 0
    self.y = y or 0
    self.z = z or 0
end

return _Vector3