---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SerDing.
--- DateTime: 2019/8/10 18:26
---

local _Panel = require("Src.GUI.Panels.Panel")
local _HUD = require("Src.Core.Class")(_Panel) ---@class HUD : Panel

local _HpController = require("Src.GUI.Controller.HpController")

---@param entity Hero_SwordMan
function _HUD:Ctor(entity)
    _Panel.Ctor(self,"HUD")
    self:LoadLayout("Data/ui/layout/hud")

    self.entity = nil ---@type Hero_SwordMan

    -- init hp mp
    self.hpView = self:GetWidgetById("hp_bar")
    self.mpView = self:GetWidgetById("mp_bar")
    self.hpController = _HpController.New() ---@type HpController
    self.mpController = _HpController.New() ---@type HpController
    self.hpController:SetView(self.hpView)
    self.mpController:SetView(self.mpView)

    self:SetEntity(entity)
end

---@param entity GameObject
function _HUD:SetEntity(entity)
    self.entity = entity
    self:SetSkillShortcutsInfo()
    self:SetHmpMVC()
end

function _HUD:SetSkillShortcutsInfo()
    local skillShortcutsMap = self.entity.skillShortcutsMap
    local skillComponent = self.entity:GetComponent("SkillMgr") ---@type SkillComponent

    local skillShortcut = nil ---@type SkillShortcut
    local skillShortcutName = ""
    -- set simple skill shortcuts
    for x = 1, 6 do
        skillShortcutName = "skill_shortcut_" .. tostring(x)
        skillShortcut = self:GetWidgetById(skillShortcutName)
        if skillShortcutsMap[string.upper(skillShortcutName)] then
            skillShortcut:SetSkill(skillComponent:GetSkillIDByName(skillShortcutsMap[string.upper(skillShortcutName)]))
        end
    end
    -- set extended skill shortcuts
    for x = 1, 6 do
        skillShortcutName = "skill_shortcut_ex_" .. tostring(x)
        skillShortcut = self:GetWidgetById(skillShortcutName)
        if skillShortcutsMap[string.upper(skillShortcutName)] then
            skillShortcut:SetSkill(skillComponent:GetSkillIDByName(skillShortcutsMap[string.upper(skillShortcutName)]))
        end
    end
end

function _HUD:SetHmpMVC()
    self.hpController:SetModel(self.entity:GetModel("HP"))
    self.mpController:SetModel(self.entity:GetModel("MP"))
end

return _HUD