---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2019/8/11 23:52
---

local _Panel = require("Src.GUI.Panels.Panel")
local _Inventory = require("Src.Core.Class")(_Panel) ---@class Inventory : Panel

function _Inventory:Ctor()
    _Panel.Ctor(self, "inventory")

    self:LoadLayout("Data/ui/layout/inventory")

end

function _Inventory:Draw(x, y)


    _Panel.Draw(self, x, y)
end

function _Inventory:DispatchMessage(msg, x, y)


    _Panel.DispatchMessage(self, msg, x, y)
end

return _Inventory
