---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SerDing.
--- DateTime: 2019/8/10 21:04
---

---@class Queue
local Queue = require("Src.Core.Class")()

function Queue:Ctor(capacity)
    self.array = { nil, nil, nil, nil, nil, nil, nil, nil} -- make the table capcity
    self.capacity = capacity
    self.front = 1
    self.rear = 1
    self.size = 0
end

function Queue:Enqueue(e)
    assert(not self:IsFull(), "queue is full.")
    self.array[self.rear] = e
    self.rear = self.rear % self.capacity + 1
    self.size = self.size + 1
end

function Queue:Dequeue()
    assert(not self:IsEmpty(), "queue is full.")
    local item = self.array[self.front]
    self.front = self.front % self.capacity + 1
    self.size = self.size - 1
    return item
end

function Queue:Contains(e)
    for i = 1, self.array do
        if self.array[i] == e then
            return true
        end
    end
    return false
end

function Queue:Clear()
    self.array = {}
end

function Queue:IsFull()
    return self.size == self.capacity
end

function Queue:IsEmpty()
    return self.size == 0
end

return Queue